# Generate github metadata file action.yml for generating db migrations
name: 'DB Migrations'
description: 'Run DB migrations'
branding:
  icon: 'database'
  color: 'purple'
inputs:
  repo_token:
    description: 'Github token'
    required: true
  migration_config_file:
    description: 'Migration configuration file'
    default: './db.migration.json'
  aws_access_key_id:
    description: AWS Access Key ID
    required: false
  aws_access_key_secret:
    description: AWS Access Secret
    required: false
  aws_region:
    description: AWS Region
    required: false
    default: ap-south-1
  aws_endpoint_url:
    description: AWS API Endpoint URL
    required: false
  debug:
    description: 'show debug logs (true|false)'
    default: 'false'

runs:
  using: composite
  steps:
    - name: Print GitHub Context
      shell: bash
      run: echo "${{ toJson(github) }}"
    - name: checkout repo
      uses: actions/checkout@v3
    - name: migration approvals
      shell: bash
      run: node $GITHUB_ACTION_PATH/dist/index.js
      env:
        INPUT_REPO_TOKEN: ${{ inputs.repo_token }}
        INPUT_MIGRATION_CONFIG_FILE: ${{ inputs.migration_config_file }}
        INPUT_AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        INPUT_AWS_ACCESS_KEY_SECRET: ${{ inputs.aws_access_key_secret }}
        INPUT_AWS_ENDPOINT_URL: ${{ inputs.aws_endpoint_url }}
        INPUT_DEBUG: ${{ inputs.debug }}