#!/bin/bash

docker \
  run \
  -e RUN_LOCAL=true \
  -e USE_FIND_ALGORITHM=true \
  -e IGNORE_GITIGNORED_FILES=true \
  -e TYPESCRIPT_DEFAULT_STYLE=prettier \
  -e VALIDATE_JSCPD=false \
  -v "${PWD}":/tmp/lint \
  ghcr.io/super-linter/super-linter